---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wfbench
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/andasilva/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wfbench
  namespace: knative-functions
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  storageClassName: ""